### ISSUE TITLE
[API] GET files in database

### ISSUE THREAD

**Issue by Muphet** [totaljs/openfiles#2]
i have no idea how to do pull requests but you should fix/change one word in 
`./plugins/files/index.js`:
line 21:
FROM:
```ROUTE("+API    /api/    -files_browse/{db}         *Files   --> query");```
TO:
```ROUTE("+API    /api/    -files_browse/{db}         *Files   --> list");```
(or change action name in schema)

there is no operation query on this schema, it's called list in `files.js` line 5

**Comment by petersirka** [comment]
Hi @Muphet.
Thank you a lot! I have fixed it https://github.com/totaljs/openfiles/commit/9bc6a911a6559698722f11d7fcde5133967abe6a
